#!/bin/bash
#----------------------------------------------------
# Sample Slurm job script
#   for TACC Stampede2 KNL nodes
#----------------------------------------------------

#SBATCH -J vae_job_$(date +%Y%m%d_%H%M%S)
#SBATCH -o myjob.o%j
#SBATCH -e myjob.e%j
#SBATCH -p dev
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -t 01:30:00
#SBATCH --mail-user=isaac.buitrago@utexas.edu
#SBATCH --mail-type=all
#SBATCH -A TwitterStyleTransfer

# Other commands must follow all #SBATCH directives...

# Launch serial code...

#while getopts e:l: flag
#do
#    case "${flag}" in
#
#        e) epochs=${OPTARG};;
#       l) lr=${OPTARG};;
#    esac
#done

python3 trainer/train_vae.py --epochs 2
# ---------------------------------------------------