VOCAB_PATH: "/Users/ibuitrago/PycharmProjects/TwitterStyleTransfer-v2/data/vocab.txt"
TRAIN_PATH: "/Users/ibuitrago/PycharmProjects/TwitterStyleTransfer-v2/data/tweets.train.txt"
VALID_PATH: "/Users/ibuitrago/PycharmProjects/TwitterStyleTransfer-v2/data/tweets.train.labels"
